### ISSUE TITLE
Erro Game Server

### ISSUE THREAD

**Issue by spiteridiick** [L2jOrg/L2jOrg#143]
[ERROR][2021-05-15 11:36:46][25][SendablePacket:write:34]: Cannot invoke "java.util.List.size()" because "org.l2j.gameserver.Config.GAME_SERVER_HOSTS" is null
java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "org.l2j.gameserver.Config.GAME_SERVER_HOSTS" is null
	at org.l2j.gameserver/org.l2j.gameserver.network.authcomm.gs2as.AuthRequest.writeImpl(AuthRequest.java:42)
	at org.l2j.gameserver/org.l2j.gameserver.network.authcomm.SendablePacket.write(SendablePacket.java:32)
	at org.l2j.gameserver/org.l2j.gameserver.network.authcomm.SendablePacket.write(SendablePacket.java:26)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WritablePacket.writeDataToBuffer(WritablePacket.java:67)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WritablePacket.writeData(WritablePacket.java:47)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.write(Client.java:122)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.writeNextPacket(Client.java:113)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client$FairnessController.writeToNextClient(Client.java:326)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client$FairnessController.sendFairPacket(Client.java:320)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.writeFairPacket(Client.java:99)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.writePacket(Client.java:80)
	at org.l2j.gameserver/org.l2j.gameserver.network.authcomm.AuthServerClient.onConnected(AuthServerClient.java:57)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Connector.connect(Connector.java:205)
	at org.l2j.gameserver/org.l2j.gameserver.network.authcomm.AuthServerCommunication.connect(AuthServerCommunication.java:77)
	at org.l2j.gameserver/org.l2j.gameserver.network.authcomm.AuthServerCommunication.run(AuthServerCommunication.java:85)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
	at org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$PriorityThread.run(PriorityThreadFactory.java:58)
[ERROR][2021-05-15 11:36:46][25][SendablePacket:write:34]: Cannot invoke "java.util.List.size()" because "org.l2j.gameserver.Config.GAME_SERVER_HOSTS" is null
java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "org.l2j.gameserver.Config.GAME_SERVER_HOSTS" is null
	at org.l2j.gameserver/org.l2j.gameserver.network.authcomm.gs2as.AuthRequest.writeImpl(AuthRequest.java:42)
	at org.l2j.gameserver/org.l2j.gameserver.network.authcomm.SendablePacket.write(SendablePacket.java:32)
	at org.l2j.gameserver/org.l2j.gameserver.network.authcomm.SendablePacket.write(SendablePacket.java:26)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WritablePacket.writeDataToBuffer(WritablePacket.java:67)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WritablePacket.writeData(WritablePacket.java:47)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.write(Client.java:122)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.writeNextPacket(Client.java:113)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client$FairnessController.writeToNextClient(Client.java:326)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client$FairnessController.sendFairPacket(Client.java:320)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.writeFairPacket(Client.java:99)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.writePacket(Client.java:80)
	at org.l2j.gameserver/org.l2j.gameserver.network.authcomm.AuthServerClient.onConnected(AuthServerClient.java:57)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Connector.connect(Connector.java:205)
	at org.l2j.gameserver/org.l2j.gameserver.network.authcomm.AuthServerCommunication.connect(AuthServerCommunication.java:77)
	at org.l2j.gameserver/org.l2j.gameserver.network.authcomm.AuthServerCommunication.run(AuthServerCommunication.java:85)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
	at org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$PriorityThread.run(PriorityThreadFactory.java:58)

**Comment by Psixxo** [comment]
What protocol you use?

**Comment by spiteridiick** [comment]
306

**Comment by Psixxo** [comment]
this for pearlbear(vicochips)

**Comment by JoeAlisson** [comment]
This branch still unstable! I tried but I don't have this problem, update and try again.
