### ISSUE TITLE
Erro Eventos

### ISSUE THREAD

**Issue by spiteridiick** [L2jOrg/L2jOrg#243]
Na hora de ligar o servidor está dando o seguinte erro.

Versão: Aden-Essence

[WARN ][2021-10-03 15:43:55][1][XmlReader:parseFile:132]: Could not parse file .\data\doors.xml
java.lang.NullPointerException: Cannot invoke "org.l2j.gameserver.world.zone.type.SiegeZone.isInsideZone(int, int, int)" because the return value of "org.l2j.gameserver.model.entity.Castle.getSiegeZone()" is null
	at org.l2j.gameserver/org.l2j.gameserver.model.entity.Castle.checkIfInZone(Castle.java:219)
	at org.l2j.gameserver/org.l2j.gameserver.instancemanager.CastleManager.getCastle(CastleManager.java:116)
	at org.l2j.gameserver/org.l2j.gameserver.instancemanager.CastleManager.getCastle(CastleManager.java:124)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.instance.Door.getCastle(Door.java:198)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.instance.Door.isEnemy(Door.java:202)
	at org.l2j.gameserver/org.l2j.gameserver.network.serverpackets.StaticObject.<init>(StaticObject.java:64)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.instance.Door.broadcastStatusUpdate(Door.java:251)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.Creature.broadcastStatusUpdate(Creature.java:450)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.status.CreatureStatus.setCurrentHp(CreatureStatus.java:255)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.status.CreatureStatus.setCurrentHp(CreatureStatus.java:218)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.Creature.setCurrentHp(Creature.java:3306)
	at org.l2j.gameserver/org.l2j.gameserver.data.xml.DoorDataManager.spawnDoor(DoorDataManager.java:143)
	at org.l2j.gameserver/org.l2j.gameserver.data.xml.DoorDataManager.spawnDoor(DoorDataManager.java:127)
	at org.l2j.gameserver/org.l2j.gameserver.data.xml.DoorDataManager.lambda$parseDocument$0(DoorDataManager.java:74)
	at org.l2j.commons/org.l2j.commons.xml.XmlReader.forEach(XmlReader.java:184)
	at org.l2j.commons/org.l2j.commons.xml.XmlReader.forEach(XmlReader.java:173)
	at org.l2j.gameserver/org.l2j.gameserver.data.xml.DoorDataManager.lambda$parseDocument$1(DoorDataManager.java:74)
	at org.l2j.commons/org.l2j.commons.xml.XmlReader.forEach(XmlReader.java:184)
	at org.l2j.commons/org.l2j.commons.xml.XmlReader.forEach(XmlReader.java:173)
	at org.l2j.gameserver/org.l2j.gameserver.data.xml.DoorDataManager.parseDocument(DoorDataManager.java:74)
	at org.l2j.commons/org.l2j.commons.xml.XmlReader.parseFile(XmlReader.java:128)
	at org.l2j.gameserver/org.l2j.gameserver.util.GameXmlReader.parseDatapackFile(GameXmlReader.java:54)
	at org.l2j.gameserver/org.l2j.gameserver.data.xml.DoorDataManager.load(DoorDataManager.java:68)
	at org.l2j.gameserver/org.l2j.gameserver.data.xml.DoorDataManager.init(DoorDataManager.java:216)
	at org.l2j.gameserver/org.l2j.gameserver.world.World.init(World.java:630)
	at org.l2j.gameserver/org.l2j.gameserver.GameServer.<init>(GameServer.java:115)
	at org.l2j.gameserver/org.l2j.gameserver.GameServer.main(GameServer.java:269)
[INFO ][2021-10-03 15:43:55][1][FenceDataManager:load:74]: Loaded 1 Fences
[INFO ][2021-10-03 15:43:55][1][GameServer:printSection:353]: ------------------------------------------------=[ Class Categories ]
[INFO ][2021-10-03 15:43:55][1][CategoryManager:load:62]: Loaded 33 Categories
[INFO ][2021-10-03 15:43:55][1][GameServer:printSection:353]: ----------------------------------------------=[ Extensions Loaders ]
[INFO ][2021-10-03 15:43:55][1][LongTimeEvent:startEvent:93]: Event Chef Monkey Event active until 2023-10-25T00:00
[INFO ][2021-10-03 15:43:55][1][WalkingManager:load:94]: Loaded 0 walking routes.
[INFO ][2021-10-03 15:43:55][1][LongTimeEvent:<init>:88]: Event Eve the Fortune Teller has passed... Ignored 
[INFO ][2021-10-03 15:43:55][1][LongTimeEvent:<init>:88]: Event Happy Hours has passed... Ignored 
[INFO ][2021-10-03 15:43:55][1][LongTimeEvent:<init>:88]: Event Looking for right words has passed... Ignored 
[WARN ][2021-10-03 15:43:55][1][XmlReader:parseFile:132]: Could not parse file .\data\extension\events\squash\xmas\config.xml
java.lang.IllegalArgumentException: InputStream cannot be null
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:118)
	at org.l2j.commons/org.l2j.commons.xml.XmlReader.parseFile(XmlReader.java:128)
	at org.l2j.gameserver/org.l2j.gameserver.util.GameXmlReader.parseDatapackFile(GameXmlReader.java:54)
	at org.l2j.gameserver/org.l2j.gameserver.model.quest.LongTimeEvent$EventParser.load(LongTimeEvent.java:141)
	at org.l2j.gameserver/org.l2j.gameserver.model.quest.LongTimeEvent.<init>(LongTimeEvent.java:78)
	at org.l2j.scripts/org.l2j.scripts.events.squash.Squash.<init>(Squash.java:70)
	at org.l2j.scripts/org.l2j.scripts.events.squash.xmas.MerrySquashmas.<init>(MerrySquashmas.java:48)
	at org.l2j.scripts/org.l2j.scripts.events.squash.xmas.MerrySquashmas.provider(MerrySquashmas.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ServiceLoader$ProviderImpl.invokeFactoryMethod(ServiceLoader.java:745)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:727)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at org.l2j.gameserver/org.l2j.gameserver.ExtensionBoot.loaders(ExtensionBoot.java:54)
	at org.l2j.gameserver/org.l2j.gameserver.GameServer.<init>(GameServer.java:121)
	at org.l2j.gameserver/org.l2j.gameserver.GameServer.main(GameServer.java:269)
[INFO ][2021-10-03 15:43:55][1][LongTimeEvent:startEvent:93]: Event null active until 2021-10-04T15:43:55.404696600
[WARN ][2021-10-03 15:43:55][1][XmlReader:parseFile:132]: Could not parse file .\data\extension\events\squash\common\config.xml
java.lang.IllegalArgumentException: InputStream cannot be null
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:118)
	at org.l2j.commons/org.l2j.commons.xml.XmlReader.parseFile(XmlReader.java:128)
	at org.l2j.gameserver/org.l2j.gameserver.util.GameXmlReader.parseDatapackFile(GameXmlReader.java:54)
	at org.l2j.gameserver/org.l2j.gameserver.model.quest.LongTimeEvent$EventParser.load(LongTimeEvent.java:141)
	at org.l2j.gameserver/org.l2j.gameserver.model.quest.LongTimeEvent.<init>(LongTimeEvent.java:78)
	at org.l2j.scripts/org.l2j.scripts.events.squash.Squash.<init>(Squash.java:70)
	at org.l2j.scripts/org.l2j.scripts.events.squash.common.CommonSquash.<init>(CommonSquash.java:48)
	at org.l2j.scripts/org.l2j.scripts.events.squash.common.CommonSquash.provider(CommonSquash.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ServiceLoader$ProviderImpl.invokeFactoryMethod(ServiceLoader.java:745)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:727)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at org.l2j.gameserver/org.l2j.gameserver.ExtensionBoot.loaders(ExtensionBoot.java:54)
	at org.l2j.gameserver/org.l2j.gameserver.GameServer.<init>(GameServer.java:121)
	at org.l2j.gameserver/org.l2j.gameserver.GameServer.main(GameServer.java:269)
[INFO ][2021-10-03 15:43:55][1][LongTimeEvent:startEvent:93]: Event null active until 2021-10-04T15:43:55.404696600
[INFO ][2021-10-03 15:43:55][1][LongTimeEvent:<init>:88]: Event The Power Of Love has passed... Ignored 
[INFO ][2021-10-03 15:43:55][1][LongTimeEvent:<init>:88]: Event Total Recall has passed... Ignored 
[WARN ][2021-10-03 15:43:55][1][XmlReader:parseFile:132]: Could not parse file .\data\extension\events\squash\watermelon\config.xml
java.lang.IllegalArgumentException: InputStream cannot be null
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:118)
	at org.l2j.commons/org.l2j.commons.xml.XmlReader.parseFile(XmlReader.java:128)
	at org.l2j.gameserver/org.l2j.gameserver.util.GameXmlReader.parseDatapackFile(GameXmlReader.java:54)
	at org.l2j.gameserver/org.l2j.gameserver.model.quest.LongTimeEvent$EventParser.load(LongTimeEvent.java:141)
	at org.l2j.gameserver/org.l2j.gameserver.model.quest.LongTimeEvent.<init>(LongTimeEvent.java:78)
	at org.l2j.scripts/org.l2j.scripts.events.squash.Squash.<init>(Squash.java:70)
	at org.l2j.scripts/org.l2j.scripts.events.squash.watermelon.WatermelonNinja.<init>(WatermelonNinja.java:48)
	at org.l2j.scripts/org.l2j.scripts.events.squash.watermelon.WatermelonNinja.provider(WatermelonNinja.java:80)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ServiceLoader$ProviderImpl.invokeFactoryMethod(ServiceLoader.java:745)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:727)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at org.l2j.gameserver/org.l2j.gameserver.ExtensionBoot.loaders(ExtensionBoot.java:54)
	at org.l2j.gameserver/org.l2j.gameserver.GameServer.<init>(GameServer.java:121)
	at org.l2j.gameserver/org.l2j.gameserver.GameServer.main(GameServer.java:269)
[INFO ][2021-10-03 15:43:55][1][LongTimeEvent:startEvent:93]: Event null active until 2021-10-04T15:43:55.404696600

**Comment by therealnevax** [comment]
The Server didn't get installed correctly and is missing something. This is an easy fix.

**Comment by spiteridiick** [comment]
> O Servidor não foi instalado corretamente e está faltando alguma coisa. Esta é uma solução fácil. Eu posso ajudar via TeamViewer, se desejar.

me chame em privado

**Comment by therealnevax** [comment]
@spiteridiick DM on discord Nevax#3308
