### ISSUE TITLE
warnings and errors - protocol 272

### ISSUE THREAD

**Issue by Cz3s1ek** [L2jOrg/L2jOrg#262]
Use the fishing generate a lot of that errors 

[WARN ][2021-11-06 02:01:25][28][World:addObject:151]: Object Fresh Blue Mackerel - Tradable(45481)[110268] already exists in the world. Stack Trace: java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
org.l2j.gameserver/org.l2j.gameserver.world.World.addObject(World.java:151)
org.l2j.gameserver/org.l2j.gameserver.model.item.container.Inventory.restore(Inventory.java:675)
org.l2j.gameserver/org.l2j.gameserver.model.item.container.PlayerInventory.restore(PlayerInventory.java:582)
org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.EnterWorld.restoreItems(EnterWorld.java:316)
org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.EnterWorld.runImpl(EnterWorld.java:211)
org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.ClientPacket.run(ClientPacket.java:53)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
java.base/java.lang.Thread.run(Thread.java:833)
org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$PriorityThread.run(PriorityThreadFactory.java:58)
[WARN ][2021-11-06 02:01:25][28][World:addObject:151]: Object Fresh Blue Mackerel - Tradable(45481)[93999] already exists in the world. Stack Trace: java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
org.l2j.gameserver/org.l2j.gameserver.world.World.addObject(World.java:151)
org.l2j.gameserver/org.l2j.gameserver.model.item.container.Inventory.restore(Inventory.java:675)
org.l2j.gameserver/org.l2j.gameserver.model.item.container.PlayerInventory.restore(PlayerInventory.java:582)
org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.EnterWorld.restoreItems(EnterWorld.java:316)
org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.EnterWorld.runImpl(EnterWorld.java:211)
org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.ClientPacket.run(ClientPacket.java:53)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
java.base/java.lang.Thread.run(Thread.java:833)
org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$PriorityThread.run(PriorityThreadFactory.java:58)
[WARN ][2021-11-06 02:01:56][26][World:addObject:151]: Object Fresh Blue Mackerel - Tradable(45481)[110269] already exists in the world. Stack Trace: java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
org.l2j.gameserver/org.l2j.gameserver.world.World.addObject(World.java:151)
org.l2j.gameserver/org.l2j.gameserver.model.item.container.Inventory.restore(Inventory.java:675)
org.l2j.gameserver/org.l2j.gameserver.model.item.container.PlayerInventory.restore(PlayerInventory.java:582)
org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.EnterWorld.restoreItems(EnterWorld.java:316)
org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.EnterWorld.runImpl(EnterWorld.java:211)
org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.ClientPacket.run(ClientPacket.java:53)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
java.base/java.lang.Thread.run(Thread.java:833)

**Comment by JoeAlisson** [comment]
This log doens't seems related to fishing. Can you describe exactly what you were doing ?

**Comment by Cz3s1ek** [comment]
nothing server runing and this warning is shows on log, is looks after login character, but after update from last night is gone, dont see anymore, tonight i will apply next update with fixed fishing shots will see more :)

**Comment by Cz3s1ek** [comment]
I think is not a fishing is some went wrong with other items too, have a lot of warnings like that on log
example:
[WARN ][2021-11-09 16:31:10][27][World:addObject:151]: Object Mold Glue(4039)[51272] already exists in the world. Stack Trace: java.base/java.lang.Thread.getStackTrace(Thread.java:1610)
org.l2j.gameserver/org.l2j.gameserver.world.World.addObject(World.java:151)
org.l2j.gameserver/org.l2j.gameserver.model.item.container.ItemContainer.restore(ItemContainer.java:580)
org.l2j.gameserver/org.l2j.gameserver.model.actor.instance.Player.getWarehouse(Player.java:2325)
org.l2j.gameserver/org.l2j.gameserver.model.actor.instance.PlayerFactory.loadPlayer(PlayerFactory.java:120)
org.l2j.gameserver/org.l2j.gameserver.network.GameClient.load(GameClient.java:267)
org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.CharacterSelect.runImpl(CharacterSelect.java:96)
org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.ClientPacket.run(ClientPacket.java:53)
java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
java.base/java.lang.Thread.run(Thread.java:833)
org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$PriorityThread.run(PriorityThreadFactory.java:58)
and all is always same only item diferent and errors like this
[ERROR][2021-11-09 17:33:24][62][ServerPacket:write:73]: [[272] [Classic - Kamael [Dawn of Heroes]]: 1.7.0-RC1-ce33672 (2021-11-07T15:40:49.198+0000)] Error writing packet ExAdenaInvenCount to client [Account: filippas6 - IP: 85.72.187.157]]]
java.lang.NullPointerException: Cannot invoke "org.l2j.gameserver.model.actor.instance.Player.getAdena()" because "player" is null
	at org.l2j.gameserver/org.l2j.gameserver.network.serverpackets.ExAdenaInvenCount.writeImpl(ExAdenaInvenCount.java:35)
	at org.l2j.gameserver/org.l2j.gameserver.network.serverpackets.ServerPacket.write(ServerPacket.java:70)
	at org.l2j.gameserver/org.l2j.gameserver.network.serverpackets.ServerPacket.write(ServerPacket.java:39)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WritablePacket.writeDataToBuffer(WritablePacket.java:67)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WritablePacket.writeData(WritablePacket.java:47)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.write(Client.java:125)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.writeNextPacket(Client.java:116)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.internal.fairness.SingleBucketStrategy.doNextAction(SingleBucketStrategy.java:38)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.internal.fairness.FairnessController.nextFairAction(FairnessController.java:59)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.finishWriting(Client.java:225)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WriteHandler.completed(WriteHandler.java:48)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WriteHandler.completed(WriteHandler.java:30)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishWrite(UnixAsynchronousSocketChannelImpl.java:647)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:199)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217)
	at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:306)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR][2021-11-09 17:33:24][62][ServerPacket:write:73]: [[272] [Classic - Kamael [Dawn of Heroes]]: 1.7.0-RC1-ce33672 (2021-11-07T15:40:49.198+0000)] Error writing packet ExUserInfoInvenWeight to client [Account: filippas6 - IP: 85.72.187.157]]]
java.lang.NullPointerException: Cannot invoke "org.l2j.gameserver.model.actor.instance.Player.getObjectId()" because "player" is null
	at org.l2j.gameserver/org.l2j.gameserver.network.serverpackets.ExUserInfoInvenWeight.writeImpl(ExUserInfoInvenWeight.java:35)
	at org.l2j.gameserver/org.l2j.gameserver.network.serverpackets.ServerPacket.write(ServerPacket.java:70)
	at org.l2j.gameserver/org.l2j.gameserver.network.serverpackets.ServerPacket.write(ServerPacket.java:39)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WritablePacket.writeDataToBuffer(WritablePacket.java:67)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WritablePacket.writeData(WritablePacket.java:47)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.write(Client.java:125)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.writeNextPacket(Client.java:116)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.internal.fairness.SingleBucketStrategy.doNextAction(SingleBucketStrategy.java:38)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.internal.fairness.FairnessController.nextFairAction(FairnessController.java:59)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.finishWriting(Client.java:225)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WriteHandler.completed(WriteHandler.java:48)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WriteHandler.completed(WriteHandler.java:30)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
	at java.base/sun.nio.ch.Invoker.invokeDirect(Invoker.java:160)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.implWrite(UnixAsynchronousSocketChannelImpl.java:759)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:382)
	at java.base/sun.nio.ch.AsynchronousSocketChannelImpl.write(AsynchronousSocketChannelImpl.java:416)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Connection.write(Connection.java:91)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Connection.write(Connection.java:85)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.write(Client.java:140)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.writeNextPacket(Client.java:116)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.internal.fairness.SingleBucketStrategy.doNextAction(SingleBucketStrategy.java:38)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.internal.fairness.FairnessController.nextFairAction(FairnessController.java:59)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.writeFairPacket(Client.java:102)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.handleNotWritten(Client.java:159)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.write(Client.java:149)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.writeNextPacket(Client.java:116)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.internal.fairness.SingleBucketStrategy.doNextAction(SingleBucketStrategy.java:38)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.internal.fairness.FairnessController.nextFairAction(FairnessController.java:59)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.finishWriting(Client.java:225)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WriteHandler.completed(WriteHandler.java:48)
	at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WriteHandler.completed(WriteHandler.java:30)
	at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:129)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finishWrite(UnixAsynchronousSocketChannelImpl.java:647)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.finish(UnixAsynchronousSocketChannelImpl.java:199)
	at java.base/sun.nio.ch.UnixAsynchronousSocketChannelImpl.onEvent(UnixAsynchronousSocketChannelImpl.java:217)
	at java.base/sun.nio.ch.EPollPort$EventHandlerTask.run(EPollPort.java:306)
	at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:113)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
