### ISSUE TITLE
Epic Bosses - 272

### ISSUE THREAD

**Issue by Cz3s1ek** [L2jOrg/L2jOrg#275]
Epic bosses after agro keep follow for Player all the time over 1500 distance.
Zaken can go after you on all map, and on script is on wrong position
this is right one from client
x - 43304
y - 207032
z - -3952
Orfen go after player on all Sea of Spore,
Antharas go out from his nest, and on game console shows warning

[WARN ][2021-11-09 21:17:47][23][Quest:showError:828]: Antharas
java.lang.NullPointerException: Cannot read field "maxDistance" because "info" is null
	at org.l2j.scripts/org.l2j.scripts.ai.bosses.Antharas$AntharasSkill.checkDistanceInfo(Antharas.java:541)
	at org.l2j.scripts/org.l2j.scripts.ai.bosses.Antharas$AntharasSkill.checkCondition(Antharas.java:533)
	at org.l2j.scripts/org.l2j.scripts.ai.bosses.Antharas$SkillDecider.chooseSkill(Antharas.java:593)
	at org.l2j.scripts/org.l2j.scripts.ai.bosses.Antharas.useSkill(Antharas.java:509)
	at org.l2j.scripts/org.l2j.scripts.ai.bosses.Antharas.manageSkills(Antharas.java:501)
	at org.l2j.scripts/org.l2j.scripts.ai.bosses.Antharas.onAdvEvent(Antharas.java:161)
	at org.l2j.gameserver/org.l2j.gameserver.model.quest.Quest.notifyEvent(Quest.java:321)
	at org.l2j.gameserver/org.l2j.gameserver.model.quest.QuestTimer.run(QuestTimer.java:70)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$PriorityThread.run(PriorityThreadFactory.java:58)

Ant Queen is OK.
Baium not check yet.
Core not check yet.

**Comment by JoeAlisson** [comment]
Will be addressed in #59
